### ISSUE TITLE
Práctica: Pruebas unitarias. METZTLI

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/practica-6-de-pruebas-unitarias-metztli#1]
[Pruebas Unitarias_METZTLI.pdf](https://github.com/SistemasTecTlaxiaco/practica-6-de-pruebas-unitarias-metztli/files/8895841/Pruebas.Unitarias_METZTLI.pdf)

**Comment by IsraelNicolas61** [comment]
20/20, buen trabajo.

**Comment by josealfredo79** [comment]
bien hecho y revisado...
